name: Deploy Inspiring Quote Generator

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
                node-version: '14'

          - name: Navigate to project directory
            run: cd inspiring-quote-generator
            
          - name: Install dependencies
            run: npm install

          - name: Run lint
            run: npm run lint

          - name: Build project
            run: npm run build